"""add sms_dispatched_at to announcements

Revision ID: 1cb7e97adca8
Revises: acb23b8bc86e
Create Date: 2026-09-29 20:36:43.857652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cb7e97adca8'
down_revision = 'acb23b8bc86e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sms_dispatched_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_column('sms_dispatched_at')

    # ### end Alembic commands ###
