"""add lake_stations

Revision ID: 3bbfb2350d6f
Revises: 4542c6a834d3
Create Date: 2026-10-06 15:50:57.633193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bbfb2350d6f'
down_revision = '4542c6a834d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lake_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_no', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('coords_source', sa.String(length=100), nullable=False),
    sa.Column('coords_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lake_stations')
    # ### end Alembic commands ###
