"""add historical_water_levels

Revision ID: 4542c6a834d3
Revises: f4b751cb0702
Create Date: 2026-10-05 18:08:36.072016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4542c6a834d3'
down_revision = 'f4b751cb0702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_water_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('level_m', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historical_water_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historical_water_levels_date'), ['date'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_water_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_water_levels_date'))

    op.drop_table('historical_water_levels')
    # ### end Alembic commands ###
