"""add recorded_at to environmental_reading

Revision ID: 54f0560ea5f2
Revises: b2fa0772c2d3
Create Date: 2026-09-07 20:19:42.911997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f0560ea5f2'
down_revision = 'b2fa0772c2d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environmental_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recorded_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environmental_readings', schema=None) as batch_op:
        batch_op.drop_column('recorded_at')

    # ### end Alembic commands ###
