"""Add phone to users

Revision ID: 56729b0d3362
Revises: 1cb7e97adca8
Create Date: 2026-10-04 00:29:16.535874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56729b0d3362'
down_revision = '1cb7e97adca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
