"""add station_id to environmental_readings

Revision ID: 5ff72c032a35
Revises: 3bbfb2350d6f
Create Date: 2026-10-06 15:58:17.123658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff72c032a35'
down_revision = '3bbfb2350d6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environmental_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('station_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_environmental_readings_station_id'), ['station_id'], unique=False)
        batch_op.create_foreign_key('fk_environmental_readings_station_id', 'lake_stations', ['station_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environmental_readings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_environmental_readings_station_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_environmental_readings_station_id'))
        batch_op.drop_column('station_id')

    # ### end Alembic commands ###
