"""add system_settings and activity_logs tables

Revision ID: 95e434cf97f1
Revises: 54f0560ea5f2
Create Date: 2026-09-10 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95e434cf97f1'
down_revision = '54f0560ea5f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wind_safe_max_kmh', sa.Float(), nullable=False),
    sa.Column('wind_caution_max_kmh', sa.Float(), nullable=False),
    sa.Column('water_safe_min_m', sa.Float(), nullable=False),
    sa.Column('water_safe_max_m', sa.Float(), nullable=False),
    sa.Column('water_caution_min_m', sa.Float(), nullable=False),
    sa.Column('water_caution_max_m', sa.Float(), nullable=False),
    sa.Column('weather_safe', sa.String(length=200), nullable=False),
    sa.Column('weather_caution', sa.String(length=200), nullable=False),
    sa.Column('weather_unsafe', sa.String(length=200), nullable=False),
    sa.Column('refresh_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('admin_name', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_logs')
    op.drop_table('system_settings')
    # ### end Alembic commands ###