"""Remove wave height from environmental readings

Revision ID: ac58542886be
Revises: 5ff72c032a35
Create Date: 2026-10-10 19:25:21.443245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac58542886be'
down_revision = '5ff72c032a35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environmental_readings', schema=None) as batch_op:
        batch_op.drop_column('wave_height_m')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environmental_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wave_height_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
