"""add environmental_readings table

Revision ID: b2fa0772c2d3
Revises: 920c6d21df2d
Create Date: 2026-08-26 14:25:06.199822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2fa0772c2d3'
down_revision = '920c6d21df2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environmental_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('location_label', sa.String(length=100), nullable=False),
    sa.Column('water_level_m', sa.Float(), nullable=True),
    sa.Column('wave_height_m', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.String(length=10), nullable=True),
    sa.Column('weather_condition', sa.String(length=50), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('entered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('environmental_readings')
    # ### end Alembic commands ###
