"""add boats and trips tables

Revision ID: e219051e316d
Revises: 2aa6ca49b86a
Create Date: 2026-08-07 18:01:09.310488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e219051e316d'
down_revision = '2aa6ca49b86a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boat_id', sa.Integer(), nullable=True),
    sa.Column('crew_name', sa.String(length=100), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('route_origin', sa.String(length=100), nullable=False),
    sa.Column('route_destination', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('delay_reason', sa.String(length=255), nullable=True),
    sa.Column('cancel_reason', sa.String(length=255), nullable=True),
    sa.Column('new_departure_time', sa.DateTime(), nullable=True),
    sa.Column('coast_guard_audit_confirmed', sa.Boolean(), nullable=False),
    sa.Column('departed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['boat_id'], ['boats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    op.drop_table('boats')
    # ### end Alembic commands ###
