"""add trip updated timestamp

Revision ID: f4b751cb0702
Revises: 56729b0d3362
Create Date: 2026-10-05 11:38:01.225805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b751cb0702'
down_revision = '56729b0d3362'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("trips", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(),
                nullable=True
            )
        )

    op.execute(
        """
        UPDATE trips
        SET updated_at = departure_time
        WHERE updated_at IS NULL
        """
    )

    with op.batch_alter_table("trips", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(),
            nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
